name: Template
on:
  push:
    branches: gh-pages
  pull_request: []
jobs:
  check-template:
    name: Test lesson template
    if: github.repository == 'carpentries/styles'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        lesson: [swcarpentry/shell-novice, datacarpentry/r-intro-geospatial, librarycarpentry/lc-git]
        os: [ubuntu-latest, macos-latest, windows-latest]
    defaults:
      run:
        shell: bash # forces 'Git for Windows' on Windows
    steps:
      - name: Set up Ruby
        uses: actions/setup-ruby@main
        with:
          ruby-version: '2.7.1'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install GitHub Pages, Bundler, and kramdown gems
        run: |
          gem install github-pages bundler kramdown

      - name: Install Python modules
        run: |
          if [[ $RUNNER_OS == macOS || $RUNNER_OS == Linux ]]; then
            python3 -m pip install --upgrade pip setuptools wheel pyyaml==5.3.1 requests
          elif [[ $RUNNER_OS == Windows ]]; then
            python -m pip install --upgrade pip setuptools wheel pyyaml==5.3.1 requests
          fi

      - name: Checkout the ${{ matrix.lesson }} lesson
        uses: actions/checkout@master
        with:
          repository: ${{ matrix.lesson }}
          path: lesson
          fetch-depth: 0

      - name: Look for R-markdown files
        id: check-rmd
        working-directory: lesson
        run: |
          echo "::set-output name=count::$(shopt -s nullglob; files=($(find . -iname '*.Rmd')); echo ${#files[@]})"

      - name: Install R packages
        if: steps.check-rmd.outputs.count != 0
        run: |
          mkdir -p ~/local/R_libs
          echo 'R_LIBS_USER=~/local/R_libs/' > ~/.Renviron
          Rscript -e "install.packages(c('knitr', 'stringr', 'checkpoint', 'ggplot2'), repos = 'https://cran.rstudio.com', dependencies = TRUE, lib='~/local/R_libs/')"

      - name: Determine the proper reference to use
        id: styles-ref
        run: |
          if [[ -n "${{ github.event.pull_request.number }}" ]]; then
            echo "::set-output name=ref::refs/pull/${{ github.event.pull_request.number }}/head"
          else
            echo "::set-output name=ref::gh-pages"
          fi

      - name: Sync lesson with carpentries/styles
        working-directory: lesson
        run: |
          git config --global user.email "team@carpentries.org"
          git config --global user.name "The Carpentries Bot"
          git remote add styles https://github.com/carpentries/styles.git
          git config --local remote.styles.tagOpt --no-tags
          git fetch styles ${{ steps.styles-ref.outputs.ref }}:styles-ref
          git merge -s recursive -Xtheirs --no-commit styles-ref
          git commit -m "Sync lesson with carpentries/styles"

      - run: make site
        working-directory: lesson
